### ISSUE TITLE
Android "Run Setup" Error log

### ISSUE THREAD

**Issue by PixelEnvision** [jizc/CloudOnce#31] opened 2017-10-15 21:58 UTC
## What steps will reproduce this issue?

Repo project attached.
[TEst.zip](https://github.com/jizc/CloudOnce/files/1385869/TEst.zip)

When I run "Run setup" following error logged to the console after success dialog.

`InvalidOperationException: Operation is not valid due to the current state of the object
System.Collections.Stack.Pop () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections/Stack.cs:329)
UnityEngine.GUILayoutUtility.EndLayoutGroup () (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:323)
UnityEngine.GUILayout.EndVertical () (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayout.cs:342)
UnityEditor.EditorGUILayout.EndVertical () (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7772)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawGooglePlayGamesSetup () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:887)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawSettingsTab () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:757)
CloudOnce.Internal.Editor.CloudOnceEditor.DrawContentArea () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:716)
CloudOnce.Internal.Editor.CloudOnceEditor.OnGUI () (at Assets/Extensions/CloudOnce/Internal/Editor/CloudOnceEditor.cs:416)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:285)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:278)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:245)
`

### Expected outcome

No errors logged to the console

--
### Environment

- CloudOnce __v2.4.4__
- Unity3D __v2017.2.0f3__
- Build platform: MacOS/Editor/Android

**Comment by jizc** [comment] 2017-10-17 17:35
I am unable to reproduce the issue on Windows. Sadly I don't have easy access to a Mac to test it there.

**Comment by retNull** [comment] 2017-10-17 18:03
See http://answers.unity3d.com/questions/852155/invalidoperationexception-operation-is-not-valid-d-1.html 

Resetting the layout and restarting Unity might be the solution.  I had no problems running setup on my mac.

**Comment by PixelEnvision** [comment] 2017-10-17 18:18
Thanks for the replies,

@jizc I think it might be related to Play Services Resolver, and it still seems to be working as I've got this error after success dialog.

@retNull Thank you, but above repo project is a new clean Unity project just with CloudOnce. But It'll try it anyway, what's your Unity & MacOS versions?

**Comment by PixelEnvision** [comment] 2017-10-17 18:42
@jizc got it :)

Apparently that's a mac only bug in Unity and there is a workaround.

If you change the line 881 of CloudOnceEditor.cs to
`tmpConfig.GoogleSetupRun = GPGAndroidSetup.DoSetup(tmpConfig.GoogleAppID);GUIUtility.ExitGUI ();`
that fixes the error.

**Comment by jizc** [comment] 2017-10-17 18:51
Thank you for the fix! I'll deploy a new version very soon.

**Comment by jizc** [comment] 2017-10-17 19:07
Fixed in [v2.4.5](https://github.com/jizc/CloudOnce/releases/tag/v2.4.5)

**Closed by jizc** 2017-10-17 19:07 UTC
